SWP\Component\ContentList\Model\ContentList:
    type: mappedSuperclass
    table: swp_content_list
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
        loggable: true
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        type:
            type: string
        cacheLifeTime:
            type: integer
            nullable: true
        limit:
            type: integer
            nullable: true
            column: list_limit
        publishedAt:
            type: datetime
            nullable: true
        publishedBefore:
            type: datetime
            nullable: true
        publishedAfter:
            type: datetime
            nullable: true
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
